# Generated by Django 4.0.6 on 2022-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Defect Field')),
                ('task', models.TextField(verbose_name='FirstPersonShooter')),
            ],
        ),
    ]
