# Generated by Django 4.0.6 on 2022-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название:')),
                ('task', models.TextField(verbose_name='Описание:')),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
