# Generated by Django 4.1.6 on 2023-02-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_release_year_remove_game_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='games.release_year'),
            preserve_default=False,
        ),
    ]
