# Generated by Django 4.1.7 on 2023-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtor', models.CharField(max_length=255)),
                ('topic_question', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
