# Generated by Django 4.1.7 on 2023-02-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='authtor',
            new_name='author',
        ),
    ]
